create table u();

create table t(a int,b text);

-- users table
create table users (id int);

-- columns that have various quoting requirements
create table cols ("left" int, "select" text, "data" int, "Mixed" text, UPPER int, U&"c!006fl" uescape '!' int);

-- table names
create table PUBLIC.Accounts (id int);
create table "Public"."Users" (id int);
create table "foo"."quoted_names" ("data" int, "value" text);
create table "left" (id int);
create table "table" (id int);
create table U&"d\0061t\+000061" (id int);
create table U&"d!0061tum" uescape '!' (id int);
create table /* foo */ foo /* bar  */ . /* buzz */ bar (id int);

-- comments inside a name node
create table U&"d!0061tum" /* mid */ uescape '!' (id int);
create table t (U&"c!006fl" /* c */ uescape '!' int);
create table t (U&"c!006fl" uescape /* c */ '!' int);

-- comments inside a path
create table foo/*a*//*b*/.bar (id int);
create table foo -- a line comment
. bar (id int);

-- comments between table args
create table t (a int /*x*/, b int);
create table t (/*a*/ a int, /*b*/ b int /*c*/);
create table t (a int -- one
, b int);
create table t (a int, b int -- two
);

-- line comment before the semicolon
create table t (a int) -- one
;

create table a_very_long_schema_name.a_very_long_table_name (a_very_long_integer_column_name int, a_very_long_text_column_name text, a_very_long_qualified_type_column_name a_very_long_type_schema_name.a_very_long_type_name, U&"c!006fl" uescape '!' a_very_long_type_schema_name.a_very_long_type_name);

-- column options and constraints
create table column_features (payload text storage external compression lz4 with options options (formatter 'plain', set compression 'fast', drop obsolete) collate public."C" constraint payload_required not null default 'missing' check (length(payload) > 0) unique, nullable text null, id bigint generated by default as identity (increment by 2 minvalue 1 no maxvalue start with 10 cache 20 cycle) primary key, computed bigint generated always as (id + 1) stored, parent_id bigint references public.parents(id) match full on delete cascade on update restrict);

-- comments in every column option position
create table column_option_comments (
/*a*/ payload /*b*/ text
/*c*/ storage /*d*/ external
/*e*/ compression /*f*/ lz4
/*g*/ with /*h*/ options
/*i*/ options /*j*/ (/*k*/ add /*l*/ formatter /*m*/ 'x' /*n*/, /*o*/ set /*p*/ formatter /*q*/ 'y' /*r*/, /*s*/ drop /*t*/ formatter /*u*/)
/*v*/ collate /*w*/ public /*x*/ . /*y*/ "C"
/*z*/ constraint /*aa*/ payload_required /*ab*/ not /*ac*/ null /*ad*/ deferrable,
/*ae*/ id /*af*/ bigint /*ag*/ generated /*ah*/ by /*ai*/ default /*aj*/ as /*ak*/ identity /*al*/ (/*am*/ increment /*an*/ by /*ao*/ 2 /*ap*/ start /*aq*/ with /*ar*/ 3 /*as*/ restart /*at*/ with /*au*/ 4 /*av*/ owned /*aw*/ by /*ax*/ none /*ay*/ sequence /*az*/ name /*ba*/ public.seq /*bb*/)
);
