MERGE INTO target AS t USING source AS s ON t.id = s.id WHEN MATCHED THEN UPDATE SET value = s.value WHEN NOT MATCHED THEN INSERT (id, value) VALUES (s.id, s.value) RETURNING t.id;

WITH merged AS (MERGE INTO target USING source ON target.id = source.id WHEN MATCHED AND source.deleted THEN DELETE WHEN NOT MATCHED BY SOURCE THEN DO NOTHING WHEN NOT MATCHED BY TARGET THEN INSERT DEFAULT VALUES RETURNING target.id) SELECT * FROM merged;

MERGE INTO a_very_long_schema_name.a_very_long_target_table_name AS an_extremely_long_target_alias USING a_very_long_schema_name.a_very_long_source_table_name AS an_extremely_long_source_alias ON an_extremely_long_target_alias.organization_identifier = an_extremely_long_source_alias.organization_identifier WHEN MATCHED AND an_extremely_long_source_alias.should_update_the_existing_record THEN UPDATE SET extremely_long_descriptive_column_name = an_extremely_long_source_alias.extremely_long_descriptive_column_name WHEN NOT MATCHED BY TARGET THEN INSERT (organization_identifier, extremely_long_descriptive_column_name) OVERRIDING SYSTEM VALUE VALUES (an_extremely_long_source_alias.organization_identifier, an_extremely_long_source_alias.extremely_long_descriptive_column_name) RETURNING an_extremely_long_target_alias.organization_identifier;

MERGE INTO target t USING source1 s1 INNER JOIN source2 s2 ON s1.id = s2.id ON t.id = s1.id WHEN NOT MATCHED THEN INSERT VALUES (s1.id, s2.value);

MERGE INTO target t USING /* before left source */ source1 /* before left alias */ s1 /* before inner */ INNER /* before join */ JOIN /* before right source */ source2 /* before right alias */ s2 /* before join on */ ON /* before join condition */ s1.id = s2.id /* before merge on */ ON /* before merge condition */ t.id = s1.id WHEN MATCHED THEN DELETE;

/* before merge */ MERGE /* before into */ INTO /* before target */ ONLY /* before target open */ (/* before schema */ public /* before dot */ . /* before table */ target /* before target close */) /* before as */ AS /* before target alias */ t /* before using */ USING /* before source */ source /* before source as */ AS /* before source alias */ s /* before on */ ON /* before condition */ t.id = s.id /* before first when */ WHEN /* before matched */ MATCHED /* before and */ AND /* before predicate */ s.deleted /* before then */ THEN /* before delete */ DELETE /* before second when */ WHEN /* before second matched */ MATCHED /* before second then */ THEN /* before update */ UPDATE /* before set */ SET /* before column */ value /* before equals */ = /* before value */ s.value /* before third when */ WHEN /* before not */ NOT /* before third matched */ MATCHED /* before by */ BY /* before source keyword */ SOURCE /* before source and */ AND /* before source predicate */ t.active /* before source then */ THEN /* before do */ DO /* before nothing */ NOTHING /* before fourth when */ WHEN /* before fourth not */ NOT /* before fourth matched */ MATCHED /* before target by */ BY /* before target keyword */ TARGET /* before target then */ THEN /* before insert */ INSERT /* before columns */ (/* before id */ id /* before comma */, /* before value column */ value /* before columns close */) /* before overriding */ OVERRIDING /* before user */ USER /* before overriding value */ VALUE /* before values */ VALUES /* before row */ (/* before source id */ s.id /* before values comma */, /* before source value */ s.value /* before row close */) /* before fifth when */ WHEN NOT MATCHED THEN INSERT /* before default */ DEFAULT /* before default values */ VALUES /* before returning */ RETURNING /* before return target */ t.id /* before semicolon */;
