select
  -- array expr
  array[1,2],
  array(select 1),
  array[[1,2],[3,4]],
  -- between expr
  2  between  1  and  3,
  2  not  between  1  and  3,
  2  between  asymmetric  1  and  3,
  2  between  symmetric  1  and  3,
  -- bin expr
  1 + 1,
  1 /* before op */ + /* after op */ 1,
  2@@@2,
  true  and  false,
  ts  at  time  zone  'UTC',
  2  ^  3,
  name  collate  "C",
  name /* before collate */ collate /* before collation */ public /* before dot */ . /* before name */ "C",
  1  =  1,
  1  >=  1,
  'foo'  ilike  'F%',
  1  in  (1, 2),
  x  is  true,
  1  is  distinct  from  2,
  1  is  /* comment */  distinct  from  2,
  x  is  not  true,
  1  is  not  distinct  from  2,
  1  <  2,
  'foo'  like  'f%',
  1  <=  2,
  1  -  1,
  1  !=  2,
  1  <>  2,
  'foo'  not  ilike  'F%',
  1  not  in  (1, 2),
  'foo'  not  like  'f%',
  'foo'  not  similar  to  'f%',
  1  OPERATOR ( + )  1,
  1  OPERATOR ( PUBLIC . + )  1,
  1  OPERATOR /* before paren */ ( /* before path */ PUBLIC /* before dot */ . /* before op */ + /* after op */ ) /* after paren */ 1,
  true  or  false,
  (1, 2)  overlaps  (3, 4),
  10  %  3,
  2  >  1,
  'foo'  similar  to  'f%',
  6  /  2,
  2  *  3,
  -- call expr
  1 = ANY ( ARRAY [ 1 , 2 ] ),
  2 = ALL ( SELECT x FROM things ),
  3 = SOME ( ARRAY [ 3 ] ),
  4 /* before op */ = /* before any */ ANY /* before opening paren */ ( /* before expr */ ARRAY [ 4 ] /* before closing paren */ ) /* after any */,
  EXISTS ( SELECT 1 FROM things ),
  /* before exists */ EXISTS /* before opening paren */ ( /* before select */ SELECT 1 /* before closing paren */ ) /* after exists */,
  EXTRACT ( YEAR FROM TIMESTAMP '2001-02-16 20:38:40' ),
  EXTRACT ( 'month' FROM ts ),
  EXTRACT ( "Field" FROM ts ),
  /* before extract */ EXTRACT /* before opening paren */ ( /* before field */ DAY /* before from */ FROM /* before expr */ ts /* before closing paren */ ) /* after extract */,
  POSITION ( 'om' IN 'Thomas' ),
  /* before position */ POSITION /* before opening paren */ ( /* before substring */ 'om' /* before in */ IN /* before string */ 'Thomas' /* before closing paren */ ) /* after position */,
  SUBSTRING ( 'Thomas' FROM 2 FOR 3 ),
  SUBSTRING ( 'Thomas' FOR 3 FROM 2 ),
  SUBSTRING ( 'Thomas' FROM 2 ),
  SUBSTRING ( 'Thomas' FOR 3 ),
  SUBSTRING ( 'Thomas' SIMILAR '%#"o_a#"_' ESCAPE '#' ),
  SUBSTRING ( 'Thomas', 2, 3 ),
  SUBSTRING ( 'Thomas' /* before comma */, /* before start */ 2, /* before count */ 3 ),
  /* before substring */ SUBSTRING /* before opening paren */ ( /* before string */ 'Thomas' /* before from */ FROM /* before start */ 2 /* before for */ FOR /* before count */ 3 /* before closing paren */ ) /* after substring */,
  TRIM ( '  foo  ' ),
  TRIM ( BOTH 'x' FROM 'xfoox' ),
  TRIM ( LEADING FROM '  foo  ' ),
  TRIM ( TRAILING 'x' FROM 'foox' ),
  TRIM ( 'x' FROM 'xfoox' ),
  TRIM ( foo, bar ),
  /* before trim */ TRIM /* before opening paren */ ( /* before side */ BOTH /* before trim char */ 'x' /* before from */ FROM /* before string */ 'xfoox' /* before closing paren */ ) /* after trim */,
  date_trunc('month', now()),
  foo ( ),
  foo ( * ),
  foo ( ALL 1, 2 ),
  foo ( /* before all */ ALL /* after all */ 1 ),
  foo ( DISTINCT 1 ),
  foo ( /* before distinct */ DISTINCT /* after distinct */ 1 ),
  foo ( VARIADIC xs ),
  foo ( /* before variadic */ VARIADIC /* after variadic */ xs ),
  foo(a => 1, b := 2),
  foo(/* before name */ a /* before arrow */ => /* before value */ 1 /* before comma */, /* before arg */ b /* before assign */ := /* before value 2 */ 2),
  array_agg(x order by y desc nulls last, z asc),
  foo(a => x order by y),
  array_agg(x order by y using > nulls first),
  array_agg(x /* before order */ order /* before by */ by /* before first */ y /* before desc */ desc /* before nulls */ nulls /* before last */ last /* before comma */, /* before second */ z /* before asc */ asc),
  JSON_ARRAYAGG(v),
  JSON_ARRAYAGG(v FORMAT JSON ORDER BY sort_col DESC NULL ON NULL RETURNING jsonb FORMAT JSON),
  JSON_ARRAYAGG /* before opening paren */ (/* before value */ v /* before value format */ FORMAT /* before value json */ JSON /* before encoding */ ENCODING /* before encoding name */ UTF8 /* before order */ ORDER /* before by */ BY /* before sort */ x /* before absent */ ABSENT /* before on */ ON /* before null */ NULL /* before returning */ RETURNING /* before type */ jsonb /* before returning format */ FORMAT /* before returning json */ JSON /* before closing paren */),
  JSON_ARRAY(),
  JSON_ARRAY(1, 2 FORMAT JSON RETURNING jsonb),
  JSON_ARRAY /* before opening paren */ (/* before first */ 1 /* before comma */, /* before second */ 2 /* before format */ FORMAT /* before json */ JSON /* before encoding */ ENCODING /* before encoding name */ UTF8 /* before returning */ RETURNING /* before type */ jsonb /* before returning format */ FORMAT /* before returning json */ JSON /* before closing paren */),
  JSON_ARRAY(/* before select */ SELECT /* before target */ x /* before format */ FORMAT /* before json */ JSON /* before absent */ ABSENT /* before on */ ON /* before null */ NULL /* before returning */ RETURNING /* before type */ jsonb /* before closing paren */),
  JSON_EXISTS(doc, '$.a'),
  JSON_EXISTS(doc, '$.a' PASSING x AS foo, y AS bar TRUE ON ERROR),
  JSON_EXISTS /* before opening paren */ (/* before document */ doc /* before format */ FORMAT /* before json */ JSON /* before encoding */ ENCODING /* before encoding name */ UTF8 /* before comma */, /* before path */ '$.a' /* before passing */ PASSING /* before arg */ x /* before as */ AS /* before name */ foo /* before arg comma */, /* before second arg */ y /* before second as */ AS /* before second name */ bar /* before behavior */ DEFAULT /* before default */ false /* before on */ ON /* before error */ ERROR /* before closing paren */),
  JSON_EXISTS(doc, '$' ERROR ON ERROR),
  JSON_EXISTS(doc, '$' NULL ON ERROR),
  JSON_EXISTS(doc, '$' FALSE ON ERROR),
  JSON_EXISTS(doc, '$' UNKNOWN ON ERROR),
  JSON_EXISTS(doc, '$' EMPTY ARRAY ON ERROR),
  JSON_EXISTS(doc, '$' EMPTY OBJECT ON ERROR),
  JSON(doc),
  JSON(doc FORMAT JSON ENCODING UTF8 WITH UNIQUE KEYS),
  JSON(doc WITHOUT UNIQUE KEYS),
  JSON /* before opening paren */ (/* before expression */ doc /* before format */ FORMAT /* before json */ JSON /* before encoding */ ENCODING /* before encoding name */ UTF8 /* before without */ WITHOUT /* before unique */ UNIQUE /* before keys */ KEYS /* before closing paren */),
  JSON_OBJECTAGG(k: v),
  JSON_OBJECTAGG(k VALUE v FORMAT JSON ABSENT ON NULL WITH UNIQUE KEYS RETURNING jsonb FORMAT JSON),
  JSON_OBJECTAGG /* before opening paren */ (/* before key */ k /* before value keyword */ VALUE /* before value */ v /* before value format */ FORMAT /* before value json */ JSON /* before null */ NULL /* before on */ ON /* before second null */ NULL /* before without */ WITHOUT /* before unique */ UNIQUE /* before keys */ KEYS /* before returning */ RETURNING /* before type */ jsonb /* before returning format */ FORMAT /* before returning json */ JSON /* before closing paren */),
  JSON_OBJECT(),
  JSON_OBJECT('a', 1, 'b', 2),
  JSON_OBJECT('a': 1, 'b' VALUE 2 FORMAT JSON NULL ON NULL WITH UNIQUE KEYS RETURNING jsonb FORMAT JSON),
  JSON_OBJECT(RETURNING jsonb),
  JSON_OBJECT /* before opening paren */ (/* before key */ 'a' /* before colon */ : /* before value */ 1 /* before comma */, /* before second key */ 'b' /* before value keyword */ VALUE /* before second value */ 2 /* before format */ FORMAT /* before json */ JSON /* before absent */ ABSENT /* before on */ ON /* before null */ NULL /* before with */ WITH /* before unique */ UNIQUE /* before keys */ KEYS /* before returning */ RETURNING /* before type */ jsonb /* before returning format */ FORMAT /* before returning json */ JSON /* before closing paren */),
  public.foo(1),
  foo /* before opening paren */ ( /* before first arg */ 1 /* before comma */, /* before second arg */ 2 /* before closing paren */ ),
  percentile_cont(0.5) WITHIN GROUP (ORDER BY x),
  mode() WITHIN GROUP (ORDER BY y DESC),
  percentile_disc(0.5) /* before within */ WITHIN /* before group */ GROUP /* before opening paren */ ( /* before order */ ORDER /* before by */ BY /* before sort */ x /* before closing paren */ ) /* after within */,
  count(*) FILTER (WHERE x > 1),
  sum(x) /* before filter */ FILTER /* before opening paren */ ( /* before where */ WHERE /* before expr */ x > 0 /* before closing paren */ ) /* after filter */,
  first_value(x) IGNORE NULLS,
  last_value(y) RESPECT NULLS,
  first_value(x) /* before treatment */ IGNORE /* before nulls */ NULLS /* after nulls */,
  sum(x) OVER window_name,
  count(*) OVER (),
  avg(x) OVER (w PARTITION BY a, b ORDER BY c DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW EXCLUDE TIES),
  sum(x) OVER (RANGE 1 PRECEDING),
  sum(x) OVER (GROUPS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING EXCLUDE GROUP),
  sum(x) OVER (ROWS BETWEEN 1 PRECEDING AND 2 FOLLOWING EXCLUDE NO OTHERS),
  sum(x) /* before over */ OVER /* before target */ ( /* before partition */ PARTITION /* before by */ BY /* before expr */ a /* before comma */, /* before second */ b /* before order */ ORDER /* before order by */ BY /* before sort */ c /* before rows */ ROWS /* before between */ BETWEEN /* before start */ 1 /* before preceding */ PRECEDING /* before and */ AND /* before end */ CURRENT /* before row */ ROW /* before exclude */ EXCLUDE /* before ties */ TIES /* before close */ ) /* after over */,
  -- case expr
  case when x > 1 then 1 else 0 end,
  case x when 1 then 'one' when 2 then 'two' else 'other' end,
  case a_very_long_input_expression when a_very_long_condition_expression then 'a very long result value for the first condition' when another_very_long_condition_expression then 'another very long result value for the second condition' else 'a very long fallback result value' end,
  case when true then 1 end,
  case /* after case */ x /* before when */ when /* after when */ 1 /* before then */ then /* after then */ 2 /* before else */ else /* after else */ 3 /* before end */ end,
  -- cast expr
  cast(1 as int8),
  treat(2 as bigint),
  1::int8,
  int8 '1',
  -- field expr
  foo . bar,
  foo.bar.baz,
  foo . *,
  (foo) . bar,
  ( /* after opening paren */ foo /* before closing paren */ ) . bar,
  foo /* before dot */ . /* before field */ "bar",
  -- index expr
  a [ 1 ],
  a[1][2],
  a[1 + 2],
  a /* before bracket */ [ /* before index */ 1 /* before closing bracket */ ],
  -- literal
  42,
  -- name ref
  FOO,
  "foo",
  "Mixed",
  U&"@0066@006f@006f" UESCAPE '@',
  -- paren expr
  ( 1 ),
  ( 1 + 2 ),
  ( ( 1 ) ),
  ( /* before expr */ 1 /* before closing paren */ ),
  -- postfix expr
  1  isnull,
  2  notnull,
  x  is  json,
  x  is  json  with  unique  keys,
  x  is  json  without  unique  keys,
  x  is  json  array,
  x  is  json  array  with  unique  keys,
  x  is  json  object,
  x  is  json  scalar,
  x  is  json  value,
  x  is  normalized,
  x  is  nfc  normalized,
  x  is  not  json,
  x  is  not  json  array,
  x  is  not  json  object,
  x  is  not  json  scalar,
  x  is  not  json  value,
  x  is  not  normalized,
  x  is  not  nfkd  normalized,
  -- prefix expr
  @-@ 10,
  OPERATOR ( PUBLIC . + ) /* after op */ 1,
  + 1,
  - 1,
  not true,
  -- slice expr
  c[:2][2:],
  c[1:2],
  c[2:],
  c[:3],
  c[:],
  c /* before bracket */ [ /* before start */ 1 /* before colon */ : /* before end */ 2 /* before closing bracket */ ],
  -- tuple expr
  ( 1 , 2 , 3 ),
  row ( ),
  row ( 1 ),
  row /* before opening paren */ ( 1 ),
  row ( 1 , 2 ),
  ( /* before first */ 1 /* before comma */ , /* before second */ 2 /* before closing paren */ );
