select
  -- array expr
  array[1,2],
  array(select 1),
  array[[1,2],[3,4]],
  -- between expr
  2  between  1  and  3,
  2  not  between  1  and  3,
  2  between  asymmetric  1  and  3,
  2  between  symmetric  1  and  3,
  -- bin expr
  1 + 1,
  1 /* before op */ + /* after op */ 1,
  2@@@2,
  true  and  false,
  ts  at  time  zone  'UTC',
  2  ^  3,
  name  collate  "C",
  1  =  1,
  1  >=  1,
  'foo'  ilike  'F%',
  1  in  (1, 2),
  x  is  true,
  1  is  distinct  from  2,
  1  is  /* comment */  distinct  from  2,
  x  is  not  true,
  1  is  not  distinct  from  2,
  1  <  2,
  'foo'  like  'f%',
  1  <=  2,
  1  -  1,
  1  !=  2,
  1  <>  2,
  'foo'  not  ilike  'F%',
  1  not  in  (1, 2),
  'foo'  not  like  'f%',
  'foo'  not  similar  to  'f%',
  1  OPERATOR ( + )  1,
  1  OPERATOR ( PUBLIC . + )  1,
  1  OPERATOR /* before paren */ ( /* before path */ PUBLIC /* before dot */ . /* before op */ + /* after op */ ) /* after paren */ 1,
  true  or  false,
  (1, 2)  overlaps  (3, 4),
  10  %  3,
  2  >  1,
  'foo'  similar  to  'f%',
  6  /  2,
  2  *  3,
  -- call expr
  date_trunc('month', now()),
  foo ( ),
  foo ( * ),
  foo ( ALL 1, 2 ),
  foo ( /* before all */ ALL /* after all */ 1 ),
  foo ( DISTINCT 1 ),
  foo ( /* before distinct */ DISTINCT /* after distinct */ 1 ),
  foo ( VARIADIC xs ),
  foo ( /* before variadic */ VARIADIC /* after variadic */ xs ),
  public.foo(1),
  foo /* before opening paren */ ( /* before first arg */ 1 /* before comma */, /* before second arg */ 2 /* before closing paren */ ),
  -- case expr
  case when x > 1 then 1 else 0 end,
  case x when 1 then 'one' when 2 then 'two' else 'other' end,
  case a_very_long_input_expression when a_very_long_condition_expression then 'a very long result value for the first condition' when another_very_long_condition_expression then 'another very long result value for the second condition' else 'a very long fallback result value' end,
  case when true then 1 end,
  case /* after case */ x /* before when */ when /* after when */ 1 /* before then */ then /* after then */ 2 /* before else */ else /* after else */ 3 /* before end */ end,
  -- cast expr
  cast(1 as int8),
  treat(2 as bigint),
  1::int8,
  int8 '1',
  -- field expr
  foo . bar,
  foo.bar.baz,
  foo . *,
  (foo) . bar,
  ( /* after opening paren */ foo /* before closing paren */ ) . bar,
  foo /* before dot */ . /* before field */ "bar",
  -- index expr
  a [ 1 ],
  a[1][2],
  a[1 + 2],
  a /* before bracket */ [ /* before index */ 1 /* before closing bracket */ ],
  -- literal
  42,
  -- name ref
  FOO,
  "foo",
  "Mixed",
  U&"@0066@006f@006f" UESCAPE '@',
  -- paren expr
  ( 1 ),
  ( 1 + 2 ),
  ( ( 1 ) ),
  ( /* before expr */ 1 /* before closing paren */ ),
  -- postfix expr
  1  isnull,
  2  notnull,
  x  is  json,
  x  is  json  with  unique  keys,
  x  is  json  without  unique  keys,
  x  is  json  array,
  x  is  json  array  with  unique  keys,
  x  is  json  object,
  x  is  json  scalar,
  x  is  json  value,
  x  is  normalized,
  x  is  nfc  normalized,
  x  is  not  json,
  x  is  not  json  array,
  x  is  not  json  object,
  x  is  not  json  scalar,
  x  is  not  json  value,
  x  is  not  normalized,
  x  is  not  nfkd  normalized,
  -- prefix expr
  @-@ 10,
  OPERATOR ( PUBLIC . + ) /* after op */ 1,
  + 1,
  - 1,
  not true,
  -- slice expr
  c[:2][2:],
  c[1:2],
  c[2:],
  c[:3],
  c[:],
  c /* before bracket */ [ /* before start */ 1 /* before colon */ : /* before end */ 2 /* before closing bracket */ ],
  -- tuple expr
  ( 1 , 2 , 3 ),
  row ( ),
  row ( 1 ),
  row /* before opening paren */ ( 1 ),
  row ( 1 , 2 ),
  ( /* before first */ 1 /* before comma */ , /* before second */ 2 /* before closing paren */ );
