select
  XMLELEMENT(NAME foo),
  XMLELEMENT(NAME foo, 1, 2),
  XMLELEMENT(NAME foo, XMLATTRIBUTES(a, b AS c)),
  XMLELEMENT(NAME foo, XMLATTRIBUTES(a AS attr), x, y),
  XMLELEMENT(NAME a_very_long_element_name, XMLATTRIBUTES(a_very_long_xml_attribute_expression AS a_very_long_xml_attribute_name, a_second_very_long_xml_attribute_expression AS a_second_very_long_xml_attribute_name), first_very_long_content_expression, second_very_long_content_expression, third_very_long_content_expression),
  /* before element */ XMLELEMENT /* before outer opening paren */ ( /* before name */ NAME /* before tag */ "tag" /* before attributes comma */, /* before xmlattributes */ XMLATTRIBUTES /* before attributes opening paren */ ( /* before first attribute */ a /* before as */ AS /* before attribute name */ "attr" /* before attribute comma */, /* before second attribute */ b /* before attributes closing paren */ ) /* before content comma */, /* before content */ x /* before outer closing paren */ ) /* after element */,
  XMLEXISTS('/foo' PASSING doc),
  XMLEXISTS('/foo' PASSING BY REF doc),
  XMLEXISTS('/foo' PASSING doc BY VALUE),
  XMLEXISTS(a_very_long_xml_exists_path_expression PASSING BY REF a_very_long_xml_exists_document_expression BY VALUE),
  /* before exists */ XMLEXISTS /* before opening paren */ ( /* before row */ '/foo' /* before passing */ PASSING /* before first by */ BY /* before ref */ REF /* before document */ doc /* before second by */ BY /* before value */ VALUE /* before closing paren */ ) /* after exists */,
  XMLFOREST(a, b AS foo),
  XMLFOREST(first_very_long_expression AS first_very_long_element_name, second_very_long_expression AS second_very_long_element_name),
  /* before forest */ XMLFOREST /* before opening paren */ ( /* before first expression */ a /* before as */ AS /* before tag */ "first" /* before comma */, /* before second expression */ b /* before closing paren */ ) /* after forest */,
  XMLPARSE(DOCUMENT '<foo/>' PRESERVE WHITESPACE),
  XMLPARSE(CONTENT value STRIP WHITESPACE),
  XMLPARSE(DOCUMENT a_very_long_xml_parse_document_expression_that_forces_the_xml_parse_node_to_wrap PRESERVE WHITESPACE),
  /* before parse */ XMLPARSE /* before opening paren */ ( /* before kind */ DOCUMENT /* before expression */ value /* before preserve */ PRESERVE /* before whitespace */ WHITESPACE /* before closing paren */ ) /* after parse */,
  XMLPI(NAME php),
  XMLPI(NAME php, 'echo'),
  XMLPI(NAME a_very_long_xml_processing_instruction_target, a_very_long_xml_processing_instruction_expression_that_forces_the_xml_pi_node_to_wrap),
  /* before pi */ XMLPI /* before opening paren */ ( /* before name */ NAME /* before target */ php /* before comma */, /* before expression */ 'echo' /* before closing paren */ ) /* after pi */,
  XMLROOT(doc, VERSION '1.0'),
  XMLROOT(doc, VERSION NO VALUE, STANDALONE YES),
  XMLROOT(doc, VERSION '1.0', STANDALONE NO),
  XMLROOT(doc, VERSION '1.0', STANDALONE NO VALUE),
  XMLROOT(a_very_long_xml_root_document_expression_that_forces_the_xml_root_node_to_wrap, VERSION a_very_long_xml_root_version_expression, STANDALONE NO VALUE),
  /* before root */ XMLROOT /* before opening paren */ ( /* before expression */ doc /* before version comma */, /* before version */ VERSION /* before no */ NO /* before version value */ VALUE /* before standalone comma */, /* before standalone */ STANDALONE /* before standalone no */ NO /* before standalone value */ VALUE /* before closing paren */ ) /* after root */,
  XMLSERIALIZE(DOCUMENT doc AS text),
  XMLSERIALIZE(CONTENT doc AS varchar(20) INDENT),
  XMLSERIALIZE(CONTENT doc AS text NO INDENT),
  XMLSERIALIZE(CONTENT a_long_xml_serialize_content_expression_that_forces_wrapping AS a_very_long_xml_serialize_return_type NO INDENT),
  /* before serialize */ XMLSERIALIZE /* before opening paren */ ( /* before kind */ CONTENT /* before expression */ doc /* before as */ AS /* before type */ text /* before no */ NO /* before indent */ INDENT /* before closing paren */ ) /* after serialize */;
