select
  XMLELEMENT(NAME foo),
  XMLELEMENT(NAME foo, 1, 2),
  XMLELEMENT(NAME foo, XMLATTRIBUTES(a, b AS c)),
  XMLELEMENT(NAME foo, XMLATTRIBUTES(a AS attr), x, y),
  /* before element */ XMLELEMENT /* before outer opening paren */ ( /* before name */ NAME /* before tag */ "tag" /* before attributes comma */, /* before xmlattributes */ XMLATTRIBUTES /* before attributes opening paren */ ( /* before first attribute */ a /* before as */ AS /* before attribute name */ "attr" /* before attribute comma */, /* before second attribute */ b /* before attributes closing paren */ ) /* before content comma */, /* before content */ x /* before outer closing paren */ ) /* after element */,
  XMLEXISTS('/foo' PASSING doc),
  XMLEXISTS('/foo' PASSING BY REF doc),
  XMLEXISTS('/foo' PASSING doc BY VALUE),
  /* before exists */ XMLEXISTS /* before opening paren */ ( /* before row */ '/foo' /* before passing */ PASSING /* before first by */ BY /* before ref */ REF /* before document */ doc /* before second by */ BY /* before value */ VALUE /* before closing paren */ ) /* after exists */,
  XMLFOREST(a, b AS foo),
  /* before forest */ XMLFOREST /* before opening paren */ ( /* before first expression */ a /* before as */ AS /* before tag */ "first" /* before comma */, /* before second expression */ b /* before closing paren */ ) /* after forest */,
  XMLPARSE(DOCUMENT '<foo/>' PRESERVE WHITESPACE),
  XMLPARSE(CONTENT value STRIP WHITESPACE),
  /* before parse */ XMLPARSE /* before opening paren */ ( /* before kind */ DOCUMENT /* before expression */ value /* before preserve */ PRESERVE /* before whitespace */ WHITESPACE /* before closing paren */ ) /* after parse */,
  XMLPI(NAME php),
  XMLPI(NAME php, 'echo'),
  /* before pi */ XMLPI /* before opening paren */ ( /* before name */ NAME /* before target */ php /* before comma */, /* before expression */ 'echo' /* before closing paren */ ) /* after pi */,
  XMLROOT(doc, VERSION '1.0'),
  XMLROOT(doc, VERSION NO VALUE, STANDALONE YES),
  XMLROOT(doc, VERSION '1.0', STANDALONE NO),
  XMLROOT(doc, VERSION '1.0', STANDALONE NO VALUE),
  /* before root */ XMLROOT /* before opening paren */ ( /* before expression */ doc /* before version comma */, /* before version */ VERSION /* before no */ NO /* before version value */ VALUE /* before standalone comma */, /* before standalone */ STANDALONE /* before standalone no */ NO /* before standalone value */ VALUE /* before closing paren */ ) /* after root */,
  XMLSERIALIZE(DOCUMENT doc AS text),
  XMLSERIALIZE(CONTENT doc AS varchar(20) INDENT),
  XMLSERIALIZE(CONTENT doc AS text NO INDENT),
  /* before serialize */ XMLSERIALIZE /* before opening paren */ ( /* before kind */ CONTENT /* before expression */ doc /* before as */ AS /* before type */ text /* before no */ NO /* before indent */ INDENT /* before closing paren */ ) /* after serialize */;
