use crate::{Linter, Rule, Violation};
use squawk_syntax::{
    Parse, SourceFile,
    ast::{self, AstNode},
};

pub(crate) fn ban_alter_identity(ctx: &mut Linter, parse: &Parse<SourceFile>) {
    for stmt in parse.tree().stmts() {
        if let ast::Stmt::AlterTable(table) = stmt {
            for action in table.actions() {
                if let ast::AlterTableAction::AlterColumn(column) = action
                    && let Some(option) = column.option()
                {
                    match option {
                        ast::AlterColumnOption::AddGenerated(node) => {
                            ctx.report(Violation::for_node(
                                Rule::BanAlterIdentity,
                                "Changing column identity may break inserts from existing clients."
                                    .into(),
                                node.syntax(),
                            ));
                        }
                        ast::AlterColumnOption::DropIdentity(node) => {
                            ctx.report(Violation::for_node(
                                Rule::BanAlterIdentity,
                                "Changing column identity may break inserts from existing clients."
                                    .into(),
                                node.syntax(),
                            ));
                        }
                        ast::AlterColumnOption::SetGenerated(node)
                            if matches!(
                                node.generated_when(),
                                Some(ast::GeneratedWhen::GeneratedAlways(_))
                            ) =>
                        {
                            ctx.report(Violation::for_node(
                                Rule::BanAlterIdentity,
                                "Changing column identity may break inserts from existing clients."
                                    .into(),
                                node.syntax(),
                            ));
                        }
                        ast::AlterColumnOption::SetGeneratedOptions(options) => {
                            for option in options.set_generated_options() {
                                if let ast::SetGeneratedOption::SetGenerated(node) = option
                                    && matches!(
                                        node.generated_when(),
                                        Some(ast::GeneratedWhen::GeneratedAlways(_))
                                    )
                                {
                                    ctx.report(Violation::for_node(Rule::BanAlterIdentity, "Changing column identity may break inserts from existing clients.".into(), node.syntax()));
                                }
                            }
                        }
                        _ => (),
                    }
                }
            }
        }
    }
}

#[cfg(test)]
mod test {
    use crate::{
        Rule,
        test_utils::{lint_errors, lint_ok},
    };
    use insta::assert_snapshot;
    #[test]
    fn err() {
        let sql = "ALTER TABLE t ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY; ALTER TABLE t ALTER COLUMN id DROP IDENTITY; ALTER TABLE t ALTER COLUMN id SET GENERATED ALWAYS;";
        let errors = lint_errors(sql, Rule::BanAlterIdentity);
        assert_eq!(errors.matches("warning[ban-alter-identity]").count(), 3);
        assert_snapshot!(errors);
    }
    #[test]
    fn ok() {
        lint_ok(
            "ALTER TABLE t ALTER COLUMN id SET DEFAULT 1; ALTER TABLE t ALTER COLUMN id SET GENERATED BY DEFAULT;",
            Rule::BanAlterIdentity,
        );
    }
}
