[alias]
xtask = "run --package xtask --"

# wasm won't compile with lld
[target.wasm32-unknown-unknown]
rustflags = ["-Clink-arg=--no-entry"]

# github actions won't compile with lld
[target.x86_64-unknown-linux-gnu]
rustflags = []

[build]
rustflags = ["-Clink-arg=-fuse-ld=lld"]
