[package]
name = "lexer"
version = "0.0.0"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
