#!/bin/sh
set -e

if [ -n "$CI" ]; then
  cargo fmt -- --check
  cargo clippy --workspace --all-targets --all-features -- -D warnings
  cargo check --workspace --locked
else
  cargo fmt
  ./s/oxfmt
  cargo clippy --fix --allow-staged --allow-dirty --all-targets --all-features -- -D warnings
fi
