#!/bin/bash
# generate a new rule using plop and our plopfile.js configuration
#
# usage:
#	s/new-rule 'prefer big serial'
#
#
# install plop via `npm install -g plop`
#
# https://github.com/plopjs/plop
plop rule "$@"